version: '3.3'
services:
   mariadb_1:
    image: mariadb:10.5
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: campaignmanager_db_1
      MYSQL_USER: suser@%
      MYSQL_PASSWORD: password
    volumes:
      - ./sql:/docker-entrypoint-initdb.d:ro
   mariadb_2:
    image: mariadb:10.5
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: campaignmanager_db_2
      MYSQL_USER: suser@%
      MYSQL_PASSWORD: password
    volumes:
      - ./sql:/docker-entrypoint-initdb.d:ro
   campaignmanager:
    container_name: campaign-manager
    build: .
    ports:
    - "9000:8080"
    - "9001:8081"
    - "5005:5005"
    volumes:
    - /var/log/campaign-manager
    environment:
      LOG_LEVEL: DEBUG
      SHARD0_CONNECTION_STRING: jdbc:mariadb://mariadb_1/campaignmanager_db_1?createDatabaseIfNotExist=true
      SHARD1_CONNECTION_STRING: jdbc:mariadb://mariadb_2/campaignmanager_db_2?createDatabaseIfNotExist=true
      DB_USER: root
      DB_PASSWORD: password
      AUTH_ENABLED: "false"
      JWT_PRIVATE_KEY: ${JWT_PRIVATE_KEY}
      SERVER_ENDPOINT: http://localhost:9000
      SECURE_ENDPOINT: "false"
      GOOGLE_DOMAIN: projectstepone.org
      PROVIDER_CALLBACK_ENDPOINT: "http://localhost:9000"
      KALEYRA_SMS_KEY: ${KALEYRA_SMS_KEY}
      KALEYRA_SMS_SENDERS: ${KALEYRA_SMS_SENDERS}
      KALEYRA_IVR_KEY: ${KALEYRA_IVR_KEY}
      KALEYRA_ENTITY_ID: ${KALEYRA_ENTITY_ID}
      JAVA_OPTS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005"
      IDMAN_ENDPOINT: ${IDMAN_ENDPOINT}
      IDMAN_SECRET: ${IDMAN_SECRET}

    depends_on:
      - mariadb_1
      - mariadb_2
