version: '2'
services:
   mariadb_1:
    image: mariadb:10.0.38
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: campaignmanager_db_1
      MYSQL_USER: suser@%
      MYSQL_PASSWORD: password
   mariadb_2:
    image: mariadb:10.0.38
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: campaignmanager_db_2
      MYSQL_USER: suser@%
      MYSQL_PASSWORD: password
   campaignmanager:
    container_name: campaign-manager
    build: .
    ports:
    - "8080:8080"
    - "8081:8081"
    - "5005:5005"
    volumes:
    - /var/log/campaign-manager
    environment:
      LOG_LEVEL: DEBUG
      SHARD0_CONNECTION_STRING: jdbc:mariadb://mariadb_1/campaignmanager_db_1?createDatabaseIfNotExist=true
      SHARD1_CONNECTION_STRING: jdbc:mariadb://mariadb_2/campaignmanager_db_2?createDatabaseIfNotExist=true
      DB_USER: root
      DB_PASSWORD: password
      AUTH_ENABLED: "true"
      JWT_PRIVATE_KEY: ${JWT_PRIVATE_KEY}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      SERVER_ENDPOINT: localhost:8080
      SECURE_ENDPOINT: "false"
      GOOGLE_DOMAIN: projectstepone.org
      KALEYRA_SMS_KEY: ${KALEYRA_SMS_KEY}
      KALEYRA_SMS_SENDERS: ${KALEYRA_SMS_SENDERS}
      KALEYRA_IVR_KEY: ${KALEYRA_IVR_KEY}
      JAVA_OPTS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005"
      PROVIDER_CALLBACK_ENDPOINT: "http://localhost:8080"

    depends_on:
      - mariadb_1
      - mariadb_2
